unbind r
bind r source-file ~/.tmux.conf

# set-option -g set-clipboard on
set -s set-clipboard on
# bind-key -T copy-mode-vi y send -X copy-selection-and-cancel ; run-shell "tmux save-buffer - | xclip -selection clipboard -in"
# set -s copy-command "tmux save-buffer - | xclip -selection clipboard -in"
# bind-key y run-shell "tmux save-buffer - | xclip -in -selection clipboard"
# bind-key -T copy-mode-vi y send-keys -X copy-selection
set -s copy-command "xclip -selection clipboard -in"





set -g base-index 1
set -g mouse on

unbind x
bind x kill-pane

unbind & # kill window 1
unbind é # kill window 
unbind '"' #  keep this one to split term v
unbind "'" # kill window
unbind ( # kill window
unbind - # kill window
unbind è # kill window 
unbind _ # kill window 
unbind ç # kill window  9
bind-key f kill-window
bind-key & select-window -t :1
bind-key é select-window -t :2
bind-key '"' select-window -t :3
# bind-key e select-window -t :3
bind-key "'" select-window -t :4
bind-key ( select-window -t :5
bind-key - select-window -t :6
bind-key è select-window -t :7
bind-key _ select-window -t :8
bind-key ç select-window -t :9

unbind e
bind-key e split-window -v

# terminal scrolling (to get the vi keybinds)
setw -g mode-keys vi
# unbind Escape-dd

bind w kill-session

set-option -g prefix M-d


# fix backround color in nvim
set -g terminal-overrides ',xterm-256color:Tc'
set -g default-terminal "screen-256color"
set -as terminal-overrides ',xterm*:sitm=\E[3m'



#act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @resurrect-strategy-nvim 'session'

# available plugins: battery, cpu-usage, git, gpu-usage, ram-usage, tmux-ram-usage, network, network-bandwidth, network-ping, attached-clients, network-vpn, weather, time, spotify-tui, kubernetes-context, synchronize-panes
# set -g @dracula-plugins "ram-usage battery time"

# available colors: white, gray, dark_gray, light_purple, dark_purple, cyan, green, orange, red, pink, yellow
# set -g @dracula-[plugin-name]-colors "[background] [foreground]"
# set -g @dracula-cpu-usage-colors "dark_gray white"
# set -g @dracula-battery-colors "green dark_gray"
# set -g @dracula-time-colors "orange dark_gray"




# set -g @dracula-show-powerline true
# set -g @dracula-fixed-location "Paris"
# set -g @dracula-plugins "weather"
# set -g @dracula-show-fahrenheit false
# set -g @dracula-day-month true
# set -g @dracula-military-time true
# set -g @dracula-border-contrast true
# set -g @dracula-battery-label "Bat"
# set -g @dracula-show-empty-plugins false
# set -g @dracula-ram-usage-label "\r"
# set -g @dracula-show-flags true
# set -g @dracula-cpu-usage-label "CPU"
# set -g @dracula-cpu-display-load true
# set -g @dracula-show-left-icon session 
# set -g status-position top

set -g @plugin 'tmux-plugins/tmux-yank'


run '~/.tmux/plugins/tpm/tpm'


